### ISSUE TITLE
Azure China

### ISSUE THREAD

**Issue by StevenLYong** [microsoft/vscode-azurevirtualmachines#100]
I tried to add SSH to my Azure China VM, but it was running about 1 hours and pop up an error message ' long time running'

**Comment by nturinski** [comment]
Hi @StevenLYong 

I'm not sure if we can help you with this.  You might be able to get around this through the portal, but this seems like a platform issue.  We were having stability issues connecting to VMs in China with our testing as well.

**Comment by nturinski** [comment]
Are you using an Azure Mooncake subscription by chance?

**Comment by nturinski** [comment]
Closing due to lack of response.  Please feel free to reopen with additional information.

Happy coding!
