### ISSUE TITLE
Internal error: Expected value to be neither null nor undefined: id

### ISSUE THREAD

**Issue by restlessankyyy** [microsoft/vscode-azurevirtualmachines#104]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.addSshKey
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: id

Version: 0.1.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code - Insiders
Product Version: 1.46.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:1:147357
Object.nonNullValueAndProp extension.bundle.js:1:147588
VirtualMachineTreeItem.<anonymous> extension.bundle.js:1:217766
fulfilled extension.bundle.js:1:215989
processTicksAndRejections task_queues.js:93:5
```

</details>

**Comment by nturinski** [comment]
Would you happen to have any repro steps for this?

**Comment by restlessankyyy** [comment]
just install vscode insider and Remote SSH plugin. Try sshing into linux VM using a Windows VM. 

Am I missing any steps please guide.

**Comment by restlessankyyy** [comment]
I think it has been taken care of. Thanks for coming back.
