### ISSUE TITLE
[Suggestion] Add a log "Generated public/private rsa key pair..." in output panel when creating a VM

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#115]
**OS:** All
**Build Version:** 20200616.3

**Repro Steps:**
Create a new VM from VS Code and check the output logs.

**Actual:**
There is a log "Generating public/private rsa key pair..." but no log about "Generated public/private rsa key pair..." in output panel.
![image](https://user-images.githubusercontent.com/45614674/84748008-a2fe3c00-afea-11ea-9048-248e8f199aad.png)

**Suggestion:**
Add a log "Generated public/private rsa key pair..." in output panel when creating a VM.

**Comment by nturinski** [comment]
Since it's a short action, I'll change it to display after it is generated.
