### ISSUE TITLE
[Suggestion] Prompt a clear dialog instead of "The connection timed out" when connecting to a stopped VM

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#117]
**OS:** All
**Build Version:** 20200616.3

**Repro Steps:**
1. Create a VM from VS Code and stop it.
2. Try to connect to VM via Remote SSH.

**Actual:**
An error "The connection timed out" occurs.
![image](https://user-images.githubusercontent.com/45614674/84755629-6cc5ba00-aff4-11ea-997c-ffa686d1d365.png)

**Suggestion:**
Prompt a clear dialog to remind user to check the VM status, such as "Please make sure the VM is running" instead of "The connection timed out".

**Comment by nturinski** [comment]
Unfortunately this isn't something that we can control from that entry point.  However, we can check before we try to run it from the extension via https://github.com/microsoft/vscode-azurevirtualmachines/issues/105
