### ISSUE TITLE
Extension not usable with a remote connection

### ISSUE THREAD

**Issue by kazssym** [microsoft/vscode-azurevirtualmachines#126]
The Azure Virtual Machines extension cannot be activated while working with a remote connection since it requires the Azure Account extension which is not loaded locally on the UI.

It should disable itself for remote connections until the Azure Account extension is updated to be usable from a UI extension.

**Comment by nturinski** [comment]
If this is blocking you, you can set the extension to run as a workspace extension by following the instructions here: https://code.visualstudio.com/api/advanced-topics/remote-extensions

**Comment by kazssym** [comment]
> If this is blocking you, you can set the extension to run as a workspace extension by following the instructions here: https://code.visualstudio.com/api/advanced-topics/remote-extensions

Not blocking at all. Thanks.
