### ISSUE TITLE
There is an error during creating two virtual machines with the same name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurevirtualmachines#132]
**OS:**
**Build Version:**

**Repro Step:**

1. Create the first virtual machine.
2. Create the second virtual machine with the same name during creating the first virtual machine.
3. Check the result.

**Expect:**
There is no error during creating two virtual machines.

**Actual:**
There is an error during creating two virtual machines.
![image](https://user-images.githubusercontent.com/62053665/90111304-09040700-dd81-11ea-9b1f-409a24f31a83.png)

**Comment by nturinski** [comment]
This is happening because the creating node doesn't have a unique id (since the subscription and the VM names are the same).  This automatically resolves itself when the VM is finished creating because the tree gets refreshed with the new tree item.
