### ISSUE TITLE
[Suggestion] Keep the name of resource group consistent between the Azure view and the Output

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurevirtualmachines#133]
**OS:** Mac
**Build:** 20200817.1

**Repro Steps:**
1. F1 --> Create Virtual Machine...(Advanced) --> Enter a name "nicole-SUSE" --> Enter a passphrase and confirm --> Select an image --> Select a location.
2. Check the logs in the Output.

**Actual:**
The name of resource group is inconsistent between the Azure view and the Output.
Azure view:
![image](https://user-images.githubusercontent.com/57662131/90478584-ea768500-e15f-11ea-9d46-c3dd1f06a79c.png)
Output:
![image](https://user-images.githubusercontent.com/57662131/90478622-fa8e6480-e15f-11ea-989b-03b594a3004e.png)

**Suggestion:**
 Make the name of resource group consistent between the Azure view and the Output.

**More Info:**
The name of resource group is consistent between the Azure view and the portal.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurevirtualmachines/pull/150
