### ISSUE TITLE
Pop up an error when creating a new VM

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurevirtualmachines#15]
**OS:** Windows

**Repro Steps:**
1. Select "Create Virtual Machine..." --> Complete the prompts according to the notifications.
2. Check the result.

**Expect:**
Succeed to create the new VM.

**Actual:**
Pop up an error when creating a new VM like below screenshot:
![image](https://user-images.githubusercontent.com/34729092/74904212-333fb380-5360-11ea-89f8-530864abdb6d.png)

**Comment by nturinski** [comment]
Could you please try this again?  I think I fixed this issue with this PR. https://github.com/microsoft/vscode-azurevirtualmachines/pull/24 I changed the way I look for the SSH key.

**Comment by fiveisprime** [comment]
When did you fix this? I'm seeing it now

```sh
5:59:00 PM: Creating resource group "mh" in location "eastus"...
5:59:02 PM: Successfully created resource group "mh".
5:59:02 PM: Creating new public IP addresss "mh-ip"...
5:59:52 PM: Created new public IP addresss "mh-ip".
5:59:52 PM: Creating new virtual network "mh-vnet"...
6:00:27 PM: Created new virtual network "mh-vnet"...
6:00:27 PM: Creating new subnet "default"...
6:00:58 PM: Created new subnet "default"
6:00:58 PM: Creating new network interface "mh826"...
6:01:03 PM: Created new network interface "mh826".
6:01:03 PM: Creating new network security group "mh-nsg"...
6:01:38 PM: Created new network security group "mh-nsg".
6:01:38 PM: Error: Command "type C:\Users\fivei\.ssh\azure_mh_rsa.pub " failed with exit code "1":
The system cannot find the file specified.
```

**Comment by v-dantch** [comment]
We verified this issue just now on Windows. And the new VM can be created with East Asia like below screenshot:
![image](https://user-images.githubusercontent.com/34729092/75013612-7ae63e00-5439-11ea-930e-1e011b93451a.png)

**Comment by fiveisprime** [comment]
Same, it's working now and safe to close this.

**Comment by v-dantch** [comment]
Got it. It seems that this issue has been fixed. And we will close it for now.
