### ISSUE TITLE
There is a string 'starting' next to the VM after restarting the VM

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#155]
**OS:** All
**Build Version:** 20200826.10

**Repro Steps:**
Restart a VM.

**Expect:**
There is no string 'starting' next to the VM.

**Actual:**
There is a string 'starting' next to the VM after restarting the VM.
![image](https://user-images.githubusercontent.com/45614674/91286524-20031a00-e7c1-11ea-9bf3-e194fec018ae.png)

**More Info:**
1. The string 'starting' will disappear after refreshing the Azure view.
2. This issue does not reproduce after starting a VM.

**Comment by nturinski** [comment]
Refreshing immediately after the restart returns didn't work to solve this.  I'm guessing that the restart just assumes that the boot-up will be successful returns before it actually starts up.  Seems like the only solution to this would be to refresh after the boot-up has finished.
