### ISSUE TITLE
Support private IP address for "Copy IP Address" command

### ISSUE THREAD

**Issue by sjuratov** [microsoft/vscode-azurevirtualmachines#172]
Does this occur consistently? Yes
Repro steps:

1. Right click VM in extension and choose "Copy IP address"

Notes:

1. I can see VM's *private* IP in Azure Portal
2. We don't have public IP

Action: azureVirtualMachines.copyIpAddress
Error type: Error
Error Message: Internal error: Expected value to be neither null nor undefined: id

Version: 0.2.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
nonNullValue extension.bundle.js:16:23970
Object.nonNullValueAndProp extension.bundle.js:16:24199
VirtualMachineTreeItem.<anonymous> extension.bundle.js:16:66918
fulfilled extension.bundle.js:16:65044
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
Hi @sjuratov

Thanks for reporting!  

Right now, `Copy IP Address` only will attempt to copy the public IP address, not the private.  Sorry for the inconvenience, but please get the private IP address from the portal until we can fix this.

**Comment by nturinski** [comment]
Closing in favor of https://github.com/microsoft/vscode-azurevirtualmachines/issues/273
