### ISSUE TITLE
It always keeps the "Adding SSH Public Key..." state after executing the "Add SSH Key..." command

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurevirtualmachines#174]
**OS:** Win10
**Build Version:** 20200917.3

**Repro Steps:**
1. Create a new Virtual Machine --> Right click the VM --> Click "Add SSH Key..." --> Select a public SSH Key that is different than the one used to create the VM --> Press Enter.
2. Check the result.

**Expect:**
Succeed to add SSH Key to VM.

**Actual:**
It always keeps the "Adding SSH Public Key..." state after executing the "Add SSH Key..." command.
![image](https://user-images.githubusercontent.com/57662131/93992347-0523c580-fdc0-11ea-8d71-2c5f2a4b2801.png)

**Comment by nturinski** [comment]
Does this reproduce on all VMs or only specific images?

**Comment by v-xinda** [comment]
Verified on the build 20200917.3, it doesn't reproduce. So I closed it.
