### ISSUE TITLE
There is no error when entering a reserved word "administrator" as the VM username

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#177]
**OS:** All
**Build Version:** 20201129.1

**Repro Steps:**
1. F1 -> Azure Virtual Machines: Create Virtual Machine... (Advanced) -> Enter a VM name -> Select an OS -> Select an image -> Enter a username "administrator".
2. Check whether there is an error or not.

**Expect:**
There is an error, such as the below error in portal.
![image](https://user-images.githubusercontent.com/45614674/100587062-0f67c000-332b-11eb-9420-00f9b2067f2d.png)

**Actual:**
There is no error.
![image](https://user-images.githubusercontent.com/45614674/100587240-46d66c80-332b-11eb-92c6-3ce5840c312d.png)

**More Info:**
1. This issue reproduces for Windows/Linux VM with any images.
2. There is an error when creating a VM with username "administrator".
![image](https://user-images.githubusercontent.com/45614674/100587422-7f764600-332b-11eb-9326-601d55917885.png)

**Comment by v-ruizh** [comment]
@nturinski , this issue also reproduces on the latest main build 20201217.2 which merged the PR you mentioned above. Could you help to take a look?

**Comment by nturinski** [comment]
Sorry, you're correct.  I originally had fixed it in that PR, but had reverted the changes.  Good catch!
