### ISSUE TITLE
The VM is still disconnected after clicking "Enable and Reload" button in the notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#178]
**OS:** Win 10
**Build Version:** 20201129.1

**Repro Steps:**
1. Create a VM.
2. Install "Remote-SSH" extension.
3. Navigate to remote explorer -> Right click the VM and select "Connect to Host in New Window".
4. There is a notification, click "Enable and Reload" button.
![image](https://user-images.githubusercontent.com/45614674/100593049-e21f1000-3332-11eb-9ac4-b85efb09b1d6.png)

**Expect:**
Continue to connect the VM.

**Actual:**
The VM is still disconnected.
![image](https://user-images.githubusercontent.com/45614674/100593148-04b12900-3333-11eb-9382-6187c0cc0f59.png)

**Comment by nturinski** [comment]
So when you clicked the button, did VS Code reload?

**Comment by v-ruizh** [comment]
Sorry for the late reply. This issue does not reproduce on the newer build. But the VM still can't connect due to the known issue https://github.com/microsoft/vscode-azurevirtualmachines/issues/65. Close this issue.
