### ISSUE TITLE
Adding SSH Key failed

### ISSUE THREAD

**Issue by eNipu** [microsoft/vscode-azurevirtualmachines#179]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.addSshKey
Error type: VMExtensionProvisioningError
Error Message: Long running operation failed with error: "VM has reported a failure when processing extension 'enablevmaccess'. Error message: "Enable failed: Failed to generate public key file."

More information on troubleshooting is available at https://aka.ms/vmextensionlinuxtroubleshoot ".

Version: 0.2.0
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:16:21138
AzureAsyncOperationLROPollStrategy.LROPollStrategy.getRestError extension.bundle.js:209:90823
extension.bundle.js:209:100545
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Could you please provide detailed repro steps?  Is this recurring?  Could you provide more information about the image that your VM is running?

**Comment by eNipu** [comment]
@nturinski I fixed the problem by adding my existing key-pair.
