### ISSUE TITLE
Automatically register "Microsoft.Network" namespace for createVirtualMachine

### ISSUE THREAD

**Issue by com-padriew** [microsoft/vscode-azurevirtualmachines#187]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.createVirtualMachine
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.Network'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.2.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:16:21138
extension.bundle.js:16:2819896extension.bundle.js:16:2819896
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Hi @com-padriew

It seems like the network namespace isn't registered for your subscription.  You should be able to do so through the Portal.  Here is a guide on how to do that: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types

On our end, we should just automatically register the provider for the user if we see that it isn't already.
