### ISSUE TITLE
[Suggestion] Support to start the stopped VM from Azure VM Explorer

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurevirtualmachines#19]
**OS**: Windows

**Repro Steps:**
1. Stop one VM in Azure Portal --> Back to Azure VM Explorer --> Select "Configure SSH Key..." from the context menu.
2. Complete the prompts --> Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/74911654-e533ab80-5371-11ea-9968-9d18c7cbbb5e.png)

**Actual:**
Only display "Report an issue". And the users need to open Azure Portal manually , then start the VM.

**Suggestion:**
Add a button which will open Azure Portal to start the stopped VM. Or support to start the VM from Azure VM Explorer.

**Comment by nturinski** [comment]
Rather than add a button to the error, I added context menu items to Start/Stop the VM.
