### ISSUE TITLE
The VM doesn't display in the remote explorer after creating a VM

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurevirtualmachines#194]
**OS:** Windows
**Build Version:** 20210107.8

**Repro Steps:**
1. Create a virtual machine.
2. Install the "Remote-SSH" extension --> Navigate to the remote explorer.
3. Check the VM.

**Expect:**
The VM displays in the remote explorer.

**Actual:**
The VM doesn't display in the remote explorer.

**More Info:**
1. There is no configuration messages of VM in the config file (`C:\Users\AzureTest\.ssh\config`).
2. The Linux VM will display in the remote explorer after adding SSH key to it.

**Comment by nturinski** [comment]
Could you provide more detail about how you're creating the vm?

**Comment by v-xinda** [comment]
@nturinski The steps of creating the vm as the following.
![VM](https://user-images.githubusercontent.com/57662131/104693242-47448e80-5744-11eb-8c22-a835c569408f.gif)
This issue only reproduces on the build 20210107.8. Verified this issue on the latest build 20210114.1, it doesn't reproduce.

**Comment by nturinski** [comment]
Okay, I guess it could have just been a weird bug with that build at the time.  I'll go ahead and close this for now.
