### ISSUE TITLE
Advanced Create Option

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurevirtualmachines#2]
Allow users to select:
- OS Image of VM
- Size

**Comment by nturinski** [comment]
@fiveisprime ...halp

![vmsize](https://user-images.githubusercontent.com/5290572/73896995-77e42e80-4839-11ea-94b1-c61787e618e8.gif)

**Comment by fiveisprime** [comment]
Oh Christ.. Here's how the portal handles that.

Default is Standard D2s v3
![image](https://user-images.githubusercontent.com/1186948/73970217-9b5ab800-48d1-11ea-980c-be71a73ea629.png)

When you click into change size, it's filtered down to 13 VM sizes
![image](https://user-images.githubusercontent.com/1186948/73970291-bfb69480-48d1-11ea-8fff-7d5b9ab38fa7.png)

Can you apply the same kind of filtering? We can always push people off to the portal if they need a size that we don't cover as a workaround then start adding sizes as people report they are missing.

**Comment by EricJizbaMSFT** [comment]
I guess I didn't think about the fact that without this users have no way to create a Windows VM from the extension. @nturinski @fiveisprime do we really only care about Ubuntu 18.04 for this release?

**Comment by nturinski** [comment]
An aside, but there is no SSH support for Windows VM.  I believe you can only use a username/password combination when you create the VM.

**Comment by fiveisprime** [comment]
Yes, Ubuntu is the most popular for remote SSH and cloud deployments. This allows us to ship with the most popular then start gathering feedback on what's missing.

**Comment by nturinski** [comment]
Related to https://github.com/microsoft/vscode-azurevirtualmachines/issues/107
