### ISSUE TITLE
Dynamically generate list of available images for user based on region

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#208]
**OS:** All
**Extension Build:** 20210206.1

**Repro Steps:**
1. Sign in with Azure China account.
2. Try to create a Linux VM with "Oracle Linux 7.8-Gen1" or "Red Hat Enterprise Linux 8.2 (LVM)-Gen1" in VS Code.

**Actual:**
An error "The platform image 'XXX' is not available." occurs.
![image](https://user-images.githubusercontent.com/45614674/107142302-e1c17780-6968-11eb-8cdb-ff117b08bee7.png)

**Suggestion:**
Remove the unsupported images from the image list.

**Comment by nturinski** [comment]
Right now, we hard code what images are being displayed to the user based on what the portal recommends.  If we could find an API endpoint that would smartly deliver us this information, we should switch to that endpoint.

**Comment by v-ruizh** [comment]
This issue still reproduces when creating a VM with image Windows 10 Pro, Version 1809 in VS Code. This image is removed from portal now.
![image](https://user-images.githubusercontent.com/45614674/128315765-0d3e9866-f1d1-48b6-88d5-6c7caf289bc8.png)

**Comment by alexweininger** [comment]
Looks like the portal is now showing `Windows-10  MicrosoftWindowsDesktop  20h2-pro` (offer, publisher, sku) for the Windows 10 Pro sku. We should probably update our image list to use it since the current one we have fails to deploy every time for me.

I'm not sure about the other skus that I can't deploy right now are the suse linux ones:

* `suse:sles-15-sp1-basic:gen1:latest`
* `suse:sles-15-sp1-basic:gen1:latest`

Not sure what to replace these with.

**Comment by alexweininger** [comment]
I found an endpoint that returns the list of recommended VM images from the portal. Still exploring, but we might be able to use this to populate the VM image quick pick.

https://catalogapi.azure.com/catalog/curationgrouplisting?api-version=2018-08-01-beta&group=Marketplace.FeaturedItems&returnedProperties=operatingSystem.family,id,image,freeTierEligible,legacyPlanId

**Comment by nturinski** [comment]
Might be able to use this as well:
https://www.npmjs.com/package/@azure/arm-datacatalog/v/1.1.0
https://docs.microsoft.com/en-us/rest/api/datacatalog/data-catalog-data-catalog#get
