### ISSUE TITLE
Creation order is different from other extensions

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#21]
All of the other extensions prompt for name first then auto-populate the resource group based on selected name. VMs is backwards, prompts for resource group then auto-populates name based on RG.

Is there a reason for this? It makes more sense to me to start with the name rather than RG.

**Comment by nturinski** [comment]
Yeah, the reason is that VM names don't have to be globally unique, but have to be unique to that particular RG.  If we don't prompt for RG first, there's no way to do that name validation.

**Comment by fiveisprime** [comment]
Ah, that makes sense
