### ISSUE TITLE
Cant connect to mi virtuasl machine via SSH

### ISSUE THREAD

**Issue by Bfrausto** [microsoft/vscode-azurevirtualmachines#217]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.openInRemoteSsh
Error type: TypeError
Error Message: e.config is not iterable

Version: 0.3.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:209:105977extension.bundle.js:209:105977
fulfilled extension.bundle.js:209:105181
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Could you please provide repro steps?  I haven't run into this error when using the RemoteSSH extension.
