### ISSUE TITLE
e.config is not iterable

### ISSUE THREAD

**Issue by Jing25** [microsoft/vscode-azurevirtualmachines#218]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.openInRemoteSsh
Error type: TypeError
Error Message: e.config is not iterable

Version: 0.3.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:209:105977
fulfilled extension.bundle.js:209:105181
processTicksAndRejections task_queues.js:94:5
```

</details>

<img width="317" alt="image" src="https://user-images.githubusercontent.com/27107288/110029497-62b22b80-7ce9-11eb-80d0-7a01a69bd5ed.png">

**Comment by nturinski** [comment]
Could you please provide repro steps?

Also could you try hitting `F1 >Remote-SSH: Open Configuration File` and confirm that you have a config file for your .ssh folder?

**Comment by Jing25** [comment]
So I first added a SSH key, and then clicked "connect to host via remote ssh". 

Yes, I have a config file and I can use "Remote-SSH: connect to host..." to login to the VM, but I cannot connect to it by right click and then  "connect to host via remote ssh" directly.

**Comment by nturinski** [comment]
Could you let me know what version of Remote-SSH that you're using?  And then try updating the extension if you are out of date?

**Comment by Jing25** [comment]
The version is v0.65.1. Since I just started using it and everything was installed recently, it's not very likely that it is out of date.

**Comment by nturinski** [comment]
Okay, thanks for confirming.  I just wanted to verify because they added parameters to the Remote-SSH: connect to host command recently in this PR: https://github.com/microsoft/vscode-remote-ssh/commit/85ad8193c3bdbf65ab494c1771f6fd0166298498

**Comment by ejizba** [comment]
@nturinski there's only one place we reference `.config` in our code, so this should be pretty easy to investigate: https://github.com/microsoft/vscode-azurevirtualmachines/blob/main/src/commands/openInRemoteSsh.ts#L34

**Comment by itchingpixels** [comment]
Hi! not sure if this helps, but I bumped into the same issue.

**Comment by nturinski** [comment]
Hi @itchingpixels and @Jing25 

We just released an update to the extension that should resolve this problem!  Please update and let me know if you run into any other issues 😊

Happy coding 🎉
