### ISSUE TITLE
Handle `ResourceNotFound` errors in a more clear/actionable way

### ISSUE THREAD

**Issue by Jing25** [microsoft/vscode-azurevirtualmachines#220]
Does this occur consistently? 
Repro steps:

1. I clicked the restart button accidentally when my Azure VM had been stopped (BTW, if the restart button cannot be clicked when the VM has been stopped, why not just disable it?). This causes an issue that the VM cannot be started again. After I solved the issue and moved my VM to another resource group, looks like the vscode could not connect to my VM again. I can get it's IP from the Azure website but not from vscode.
2. This error occurred when I tried copying the IP of my VM (name: Wildfire-RF-Jing) from vscode

<img width="412" alt="image" src="https://user-images.githubusercontent.com/27107288/110741927-526ae680-81ea-11eb-96ce-8b344b05a56c.png">

Action: azureVirtualMachines.copyIpAddress
Error type: ResourceNotFound
Error Message: The Resource 'Microsoft.Network/networkInterfaces/wildfire-rf-jing895' under resource group 'firevm' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix

Version: 0.3.0
OS: darwin
OS Release: 20.1.0
Product: Visual Studio Code
Product Version: 1.54.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:16:21586
extension.bundle.js:16:129786
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by Jing25** [comment]
Hi I found the problem. I'm new to Azure VM, I realized that when I moved my VM to another resource group, I didn't move related things to that group as well. It's solved. 

I'm wondering if you have any plan to disable the restart button while the VM is not running.

**Comment by nturinski** [comment]
Hi @Jing25

We currently have this issue to track disabling the restart button: https://github.com/microsoft/vscode-azurevirtualmachines/issues/223

I'm glad that you were able to find the problem!  Yeah, VM's have a bunch of resources that all get created/linked together.  I'm surprised that you were able to just _move_ your VM without any of the associated resources.  Thanks for reporting this issue; we could handle that error more user-friendlier!
