### ISSUE TITLE
boxung

### ISSUE THREAD

**Issue by duonghoanghai** [microsoft/vscode-azurevirtualmachines#229]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.createVirtualMachineAdvanced
Error type: NoResourceFoundError
Error Message: No matching resources found.

Version: 0.3.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.0
Language: en

<details>
<summary>Call Stack</summary>

```
AzureAccountTreeItem.<anonymous> extension.bundle.js:16:148798
fulfilled extension.bundle.js:16:142741
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by duonghoanghai** [comment]
Let me find a way to unplug the whole windows system, it fixes my error.
i will find a way to terrorize windows with nuclear contener vehicle. crashing into windows database is an automatic mail that fixes the error for me. they must use extreme to be good

**Comment by duonghoanghai** [comment]
Let me find a way to unplug the whole windows system, it fixes my error.
i will find a way to terrorize windows with nuclear contener vehicle. crashing into windows database is an automatic mail that fixes the error for me. they must use extreme to be good

**Comment by duonghoanghai** [comment]
Someone helping me contact my second sister, the red-tailed octopus, is just out of nowhere. I feel my sister,

**Comment by nturinski** [comment]
Thanks for contacting us regarding this error. Could you please provide repro steps so that we can assist you figure out this issue?
