### ISSUE TITLE
Use Linux path separators in .ssh/config

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#25]
This is a Linux standard and should use `/` even on Windows.

Also, the whitespace in `config` is pretty gnarly 🤢

**Comment by nturinski** [comment]
Could you confirm that the configs are less gnarly with this change?

https://github.com/microsoft/vscode-azurevirtualmachines/compare/nat/sshConfigFormat?expand=1
