### ISSUE TITLE
Fail to create the VM with "Windows10 Pro" image and "Japan West" location

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurevirtualmachines#254]
**OS:** All
**Build Version:** 20210512.8

**Repro Steps:**

1. Create an advanced VM with **Windows10 Pro**  image and **Japan West** location.
2. Check whether create the VM successfully.

**Expect:**
Succeed to create a VM with **Windows10 Pro** and **Japan West** location.

**Actual:**
Fail to create the VM with an error.
![image](https://user-images.githubusercontent.com/62053665/120303832-cb696e00-c301-11eb-9078-a1e72a893c41.png)

**More Info:**
Succeed to create a VM with **Japan West** location and other images.

**Comment by v-mengwe** [comment]
Succeed to create a VM with Windows10 Pro and Japan West location in Portal.

**Comment by v-xinda** [comment]
Verified this issue on current VS Code Stable 1.71.2 with the latest build 20220922.1 installed, this issue doesn't reproduce, close it.
