### ISSUE TITLE
There is no location in the location list when creating a new VM

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#259]
**OS:** Win10
**Build Version:** 20210623.1

**Repro Steps:**
1. F1 -> Azure Virtual Machines: Create Virtual Machine... -> Enter a VM name -> Enter a passphrase -> Navigate to "select location" list.
2. Check whether there are locations in the location list or not.

**Expect:**
There are locations in the location list.
![image](https://user-images.githubusercontent.com/45614674/123241293-996bb600-d513-11eb-9c7a-a04ee49e410e.png)

**Actual:**
There is no location in the list.
![image](https://user-images.githubusercontent.com/45614674/123241314-9c66a680-d513-11eb-92f5-a6b40ae06905.png)

**More Info:**
1. This issue also reproduces when creating an advanced VM.
2. This issue does not reproduce on the previous released VM extension 0.4.0.

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurevirtualmachines/pull/262
