### ISSUE TITLE
Set up Azure Pipelines

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurevirtualmachines#27]

**Comment by EricJizbaMSFT** [comment]
Make sure to copy the latest '.azure-pipelines' folder from functions. A few things I noticed different:
1. It uses Node 10 instead of 8
1. It has a fix for linux tests
1. It _doesn't_ have intellinav

The one thing not necessary in VMs extension is the `UsePythonVersion` task in test.yml
