### ISSUE TITLE
The VM resource group name letters in the opened .json file change to uppercase after viewing the properties of the VM

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-azurevirtualmachines#274]
**OS:** All
**Build Version:** 20210818.4

**Repro Steps:**

1. Right click a VM, e.g. "elsa-bas-test" -> Select "View Properties".
2. Check the VM resource group name letters in the opened .json file.

**Expect:**
The VM resource group name letters in the opened .json file are lowercase.
![image](https://user-images.githubusercontent.com/62053665/130039693-70281087-8c8e-4f0c-805a-f7861094bc86.png)
![image](https://user-images.githubusercontent.com/62053665/130039665-f161a9d5-f756-4a4d-8580-4fe9c0be765f.png)

**Actual:**
The VM resource group name letters in the opened .json file change to uppercase.
![image](https://user-images.githubusercontent.com/62053665/130039733-900ba05b-2514-4596-926b-bef7a9747158.png)

**More Info:**
If you can't reproduce this issue, you can execute "View Properties" after refeshing the VM.

**Comment by nturinski** [comment]
Azure automatically upper cases the resource group name for VMs for some reason.  This is unrelated to anything that we are doing.  Since the resource groups are case insensitive, this behavior shouldn't impact our users.
