### ISSUE TITLE
No error occurs when executing delete action for a deleted VM

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#289]
**OS:** Win 10
**Build Version:** 20211205.1
**Regression:** Not a regression

**Repro Steps:**
1. Create a VM in VS Code.
2. Open a new VS Code instance and delete the VM with all resources selected.
3. Navigate to the first VS Code instance without refresh, right click the VM and select "Delete" action.
4. Check whether there is an error or not.

**Expect:**
There is an error, such as "The VM has been deleted".

**Actual:**
No error occurs and the "virtual machine"/"disk" resources can be selected.
![image](https://user-images.githubusercontent.com/45614674/145008976-d31d3a50-0402-4efe-b1a1-6e2d21470ccc.png)

**More Info:**
The "virtual machine" and "disk" resources can be selected and deleted successfully.
![image](https://user-images.githubusercontent.com/45614674/145008947-7a664fbd-3d6b-4fcb-96cf-da5d98ea5bac.png)

**Comment by wwlorey** [comment]
Unfortunately this isn't something we can fix since we rely on the Azure SDKs to tell us what VMs are deleted/not deleted.
