### ISSUE TITLE
The popped up error message is not clear when creating more than 14 virtual machines with "Microsoft RRDC Lab 1" location 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurevirtualmachines#294]
**OS:** All
**Build Version:** 20220119.2
**Regression:** Not a regression

**Repro Steps:**
1. Create more than 14 new virtual machines with **Microsoft RRDC Lab 1** location.
2. Check whether the popped up error message is clear. 

**Expect:**
The popped up error message is clear. 

**Actual:**
The popped up error message is not clear. 
![image](https://user-images.githubusercontent.com/57662131/150320800-54778244-f8b6-4799-9f94-ee7c72dd194d.png)

**Comment by wwlorey** [comment]
The limit for how many machines can be created in edge zones is currently very small so this is expected behavior.
