### ISSUE TITLE
There are no "Connect to Host via Remote SSH" and "Add SSH Key…" actions in the VM context menu

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#313]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure VM Extension Build Version:** 20220421.7 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. Create a new VM.
2. Right click this VM to open its context menu.
3. Check whether there are "Connect to Host via Remote SSH" and "Add SSH Key…" actions in the context menu or not.

**Expect:**
There are "Connect to Host via Remote SSH" and "Add SSH Key…" actions in the context menu.
![image](https://user-images.githubusercontent.com/45614674/165065174-7cd5a831-0a6b-4976-aafc-5d4d9213bafc.png)

**Actual:**
There are no "Connect to Host via Remote SSH" and "Add SSH Key…" actions in the context menu.
![image](https://user-images.githubusercontent.com/45614674/165064956-0f15387e-0ee1-476e-b8e9-7ff5a1fb4561.png)

**Comment by alexweininger** [comment]
Fixed by #314
