### ISSUE TITLE
There are no "Azure Virtual Machines: Open in Portal" and "Azure Virtual Machines: View Properties" commands in command palette

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#315]
**OS:** All
**Azure Resource Extension Build Version:** 20220425.13 (unified)
**Azure VM Extension Build Version:** 20220426.1 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Search "Azure Virtual Machines" to open the command list of Azure VM.
2. Check whether there are "Azure Virtual Machines: Open in Portal" and "Azure Virtual Machines: View Properties" commands in command palette.

**Expect:**
There are "Azure Virtual Machines: Open in Portal" and "Azure Virtual Machines: View Properties" commands in command palette.
![image](https://user-images.githubusercontent.com/45614674/165269410-e80fdc37-9682-43ce-b27c-e2b1f92b9ef7.png)

**Actual:**
There are no "Azure Virtual Machines: Open in Portal" and "Azure Virtual Machines: View Properties" commands in command palette.
![image](https://user-images.githubusercontent.com/45614674/165269297-50f35aac-553d-4cd8-8be6-25930efa183e.png)

**Comment by alexweininger** [comment]
This is by design. These commands have been replaced by "Azure Resource Groups: View Properties" and "Azure Resource Groups: Open in Portal".
