### ISSUE TITLE
There is an extra "+ Create new Resource Group…" option in the command list

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#316]
**OS:** All
**Azure Resource Extension Build Version:** 20220427.11 (unified)
**Azure VM Extension Build Version:** 20220426.1 (unified)
**Regression:** Not a regression

**Repro Steps:**
1. F1 -> Azure Virtual Machines: Copy IP Address.
2. Check whether there is no "+ Create new Resource Group…" option in the command list.

**Expect:**
There is no "+ Create new Resource Group…" option in the command list.

**Actual:**
There is an extra "+ Create new Resource Group…" option in the command list.
![image](https://user-images.githubusercontent.com/45614674/165734846-d3a5570a-7c38-467b-910b-2f14704c84c4.png)

**More Info:**
1. An error occurs when selecting "+ Create new Resource Group…" to create a resource group.
![image](https://user-images.githubusercontent.com/45614674/165735744-3a1a6e4b-09bd-42e3-9326-3d56bdddd459.png)
3. This issue also reproduces for "Start/Stop/Restart/Connect to Host via Remote SSH/Add SSH Key.../Copy IP Address" commands.

**Comment by alexweininger** [comment]
Fixed by #317
