### ISSUE TITLE
The name of the resource group is inconsistent with the virtual machine's name if signing in with the Azure China account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-azurevirtualmachines#331]
**OS:** Win10
**Build Version:** 20220606.1

**Repro Steps:**
1. Sign in with the Azure China account.
2. Create a virtual machine with name "nicole-win19".
3. Check whether the name of the resource group is consistent with the virtual machine's name.

**Expect:**
The name of the resource group is consistent with the virtual machine's name.
![image](https://user-images.githubusercontent.com/57662131/172350956-4abf18e6-4b3d-4aa9-8a59-3e21a518d36f.png)

**Actual:**
The name of the resource group is inconsistent with the virtual machine's name.
![image](https://user-images.githubusercontent.com/57662131/172351301-36776fa6-4e66-4022-b3d9-dd8886dff834.png)

**More Info:**
This issue doesn't reproduce after signing in with Azure account.

**Comment by alexweininger** [comment]
Closing as a won't-fix
