### ISSUE TITLE
Change the minimum VS Code version that the Azure Virtual Machines extension supports

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-azurevirtualmachines#349]
**OS:** Win10
**Build Version:** 20221013.1

**Repro Steps:**

1. Figure out the oldest vs code version that the extension supports, the version is 1.57.0 as below.
![image](https://user-images.githubusercontent.com/107091828/195786084-9d21e67c-2c95-4992-af6a-59a8448a2809.png)
2. Install VS Code 1.57.1 from https://code.visualstudio.com/updates.
3. Install the Azure Virtual Machines extension from VSIX.
4. Expand the subscription node.
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/195786126-0ccd2505-b4b5-4ec4-a580-8338d95cea76.png)

**Comment by alexweininger** [comment]
This is now fixed as the minimum version was changed to `^1.66.0`
