### ISSUE TITLE
Match the portal when stopping VM

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-azurevirtualmachines#37]
The portal asks some questions before stopping and we don't:
![Screen Shot 2020-02-21 at 4 02 31 PM](https://user-images.githubusercontent.com/11282622/75081376-cfce9680-54c3-11ea-81b6-695bcf27c668.png)

Should probably be consistent?

**Comment by nturinski** [comment]
Seems like this behavior doesn't exist anymore:

![image](https://user-images.githubusercontent.com/5290572/91098565-87c93180-e616-11ea-95d7-af0d3cefe3f0.png)

Tried with a Linux and Windows VM

**Comment by nturinski** [comment]
So I think the new behavior is as follows:

Portal:
Stop on a running VM stops the VM.
```
The operation to power off (stop) a virtual machine. The virtual machine can be restarted with the same provisioned resources. You are still charged for this virtual machine.
```
Stop on a stopped VM deallocates the VM. (the button is still labeled Stop)
```
 Shuts down the virtual machine and releases the compute resources. You are not billed for the compute resources that this virtual machine uses.
```

In the extension, we run "deallocate" for stop.  There's another command that stops the VM called powerOff.  Not sure if that was always there, but I suggest we move to that for now and give users a way to deallocate for the next release.
