### ISSUE TITLE
An error occurs when creating a VM with "West Europe" location

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-azurevirtualmachines#376]
**OS:** Win 10
**Build Version:** 20230322.1

**Repro Steps:**
1. Create a virtual machine with "West Europe" location.
2. Check whether succeeds to create a VM with "West Europe" location.

**Expect:**
Succeed to create a VM with "West Europe" location.

**Actual:**
An error occurs when creating a VM with "West Europe" location.
![image](https://user-images.githubusercontent.com/45614674/227134925-1dd2629f-17f1-491c-a64d-9ceca0a222e9.png)

**More Info:**
1. The failed VM still shows in the VM tree view.
![image](https://user-images.githubusercontent.com/45614674/227135522-1ef2fc22-e615-4cbe-a2ce-0dab15edd7d9.png)
2. The failed VM also shows in portal.

**Comment by alexweininger** [comment]
Does this still reproduce?

**Comment by v-ruizh** [comment]
This issue does not reproduce on the VM extension build 20230405.1, close it.
