### ISSUE TITLE
VM description should show status for anything except "running"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurevirtualmachines#38]
For right now it only shows state of "stopped", but there's more states than just that
https://github.com/microsoft/vscode-azurevirtualmachines/blob/master/src/tree/VirtualMachineTreeItem.ts#L38

For example (from the portal):
![Screen Shot 2020-02-21 at 4 03 23 PM](https://user-images.githubusercontent.com/11282622/75081499-3a7fd200-54c4-11ea-8320-c611ee939453.png)

Also stopped looks different in the portal:
![Screen Shot 2020-02-21 at 4 03 51 PM](https://user-images.githubusercontent.com/11282622/75081509-41a6e000-54c4-11ea-9130-390e40cf8742.png)
I don't think "stopped" and "deallocated" are entirely interchangeable like your code implies. I believe it can be stopped, but not deallocated?

**Comment by nturinski** [comment]
The only statuses that I've seen returned at `VM running` and `VM deallocated`.  I assume `Deallocating` is while it's turning off, but since we display "Stopping" in the node, we would never see this description.

I assume that 'VM deallocated` is the same as stop since that seems to be how the portal displays it.

**Comment by EricJizbaMSFT** [comment]
> The only statuses that I've seen returned at VM running and VM deallocated.

There's almost certainly 'error' or 'unknown' states that don't happen very often, but are still very useful information.

> I assume Deallocating is while it's turning off, but since we display "Stopping" in the node, we would never see this description.

Our "Stopping" won't display if users stopped it in the portal or if they refresh the whole Azure view after stopping.

> I assume that 'VM deallocated` is the same as stop since that seems to be how the portal displays it.

https://peakup.org/blog/azure-vm-stop-vs-deallocated/

I think `computeClient.virtualMachines.powerOff` is equivalent to "stopped but not deallocated"

**Comment by nturinski** [comment]
Do you think it's best that I just display exactly what Azure returns? (minus the VM prefix and `VM running`?) I don't know all of the potential states, so this seems like the safest bet.

**Comment by EricJizbaMSFT** [comment]
Yeah sounds good
