### ISSUE TITLE
Don't prompt for resource group in basic create

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurevirtualmachines#40]
I would prefer if we prompt for the name of the VM first and just always create a new resource group. This is what we do in other extensions for a few reasons:
1. It reduces prompts
1. It hides the concept of a "resource group" which is pretty Azure-y and could be confusing to new users (aka the target audience for basic create)

**Comment by nturinski** [comment]
Makes sense, might be worth adding this to the 0.1.0 release. Wouldn't want to change the UI later after we already confuse users.

**Comment by nturinski** [comment]
@fiveisprime Opinions/thoughts on this idea and what the default rg name should be?

**Comment by fiveisprime** [comment]
Prompt for VM name, name the RG the same as the RG.

**Comment by nturinski** [comment]
Fixed by #61
