### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Flukjokrax** [microsoft/vscode-azurevirtualmachines#414]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-azurevirtualmachines/issues/413
```

**Comment by Flukjokrax** [comment]
test

**Comment by nturinski** [comment]
Closing as not an issue. If you encounter any issues with the extension, please feel free to open another issue with a detailed error and steps to reproduce it. 

Thanks!
