### ISSUE TITLE
Delete VMs

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-azurevirtualmachines#5]

**Comment by nturinski** [comment]
![image](https://user-images.githubusercontent.com/5290572/73778929-ceba0d00-4740-11ea-9897-1b0330a5aefd.png)

In this case, I don't know if we want to follow the portal's behavior.  I find it rather annoying to have to delete everything manually especially since most of these components are automatically generated.

**Comment by nturinski** [comment]
@fiveisprime

**Comment by nturinski** [comment]
Fixed by https://github.com/microsoft/vscode-azurevirtualmachines/pull/7

**Comment by fiveisprime** [comment]
Agreed, it's silly to have to delete them individually and that gets me every time.
