### ISSUE TITLE
"Add SSH Key..." doesn't work on Windows

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurevirtualmachines#50]
Repro steps:

1. Create a windows VM in the portal
2. "Add SSH Key..." in VS Code

The portal doesn't seem to support this (they only do reset password), so perhaps the best we can do is hide the context menu or pre-emptively throw a better error before even trying to add an ssh key.

Action: azureVirtualMachines.addSshKey
Error type: VMExtensionProvisioningError
Error Message: Long running operation failed with error: "VM has reported a failure when processing extension 'enablevmaccess'. Error message: "Extension '' of Handler 'Microsoft.OSTCExtensions.VMAccessForLinux' version '1.0' faulted due to exception during extension processing"

More information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot ".

Version: 0.1.0-alpha
OS: darwin
OS Release: 19.2.0
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError ms-rest-azure/pollingState.js:127:17
ms-rest-azure/azureServiceClient.js:156:38
async/async.js:958:16
next async/async.js:5211:18
ms-rest-azure/azureServiceClient.js:129:20
ms-rest-azure/azureServiceClient.js:183:5
ms-rest-azure/azureServiceClient.js:321:12
retryCallback ms-rest/systemErrorRetryPolicyFilter.js:89:9
retryCallback ms-rest/exponentialRetryPolicyFilter.js:140:9
ms-rest/rpRegistrationFilter.js:59:14
handleRedirect ms-rest/redirectFilter.js:39:9
ms-rest/formDataFilter.js:23:14
Request._callback ms-rest/requestPipeline.js:125:16
Request.callback request/request.js:185:22
Request.emit events.js:200:13
Request.<anonymous> request/request.js:1161:10
Request.emit events.js:205:15
IncomingMessage.<anonymous> request/request.js:1083:12
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by nturinski** [comment]
I think we should have Windows/Linux context values and just hide this command for Windows.

**Comment by nturinski** [comment]
Show better error message (pre-emptively)
