### ISSUE TITLE
Add output related to `configureSshConfig` while creating a VM

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurevirtualmachines#52]
I'd like to see stuff in the output that we're creating an ssh key and modifying their ssh config file. We're doing some magic here to make things simpler for users, but I think that makes logs more important.

**Comment by nturinski** [comment]
What do you think about this?

![image](https://user-images.githubusercontent.com/5290572/75382374-3b7f7d80-588f-11ea-8ab6-0284f57deee4.png)

I tried displaying the output of `ssh-keygen` but it looks real nasty.

The appending new entry line looks pretty bad with the floating quote and I'll fix that.  But I'm more curious if you think I should print off the whole entry or not.  Also would it be useful if we could hyperlink their config file to just let the user open it?

**Comment by EricJizbaMSFT** [comment]
> But I'm more curious if you think I should print off the whole entry or not

Seems excessive

>  Also would it be useful if we could hyperlink their config file to just let the user open it?

Sure
