### ISSUE TITLE
Document basic create defaults

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-azurevirtualmachines#55]
Related to https://github.com/microsoft/vscode-azurefunctions/issues/1319, we should add a wiki page saying what defaults we do (VM Size, OS, image, etc.). Also I noticed the portal only allows SSH port by default, but we allow SSH, HTTP, and HTTPS. I assume there's a reason we're different? If yes, would be nice to have that documented

**Comment by nturinski** [comment]
Closed by https://github.com/microsoft/vscode-azurevirtualmachines/wiki/Create-Virtual-Machine-defaults
