### ISSUE TITLE
There are duplicated VMs without refreshing when complete to create a VM

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-azurevirtualmachines#64]
**OS**: Windows
**Build Version**: [20200226.22](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=15259&view=results)

**Repro Steps**:
1. Select "Create Virtual Machine..." --> Type the VM name and region.
2. Click "Refresh" icon when the VM is still creating like the last step 7/7. 

**Expect**:
The refreshing doesn't effect the creating.

**Actual:**
1. There displays the VM in Azure VM Extension view even though the creating is not completed.
2. There are duplicated VMs without refreshing when complete to create VM.
![image](https://user-images.githubusercontent.com/34729092/75317937-fbcc7d80-581d-11ea-80d4-8b6cfcea615e.png)

**More Info:**
Only display one VM after refreshing.

**Comment by nturinski** [comment]
The first part still happens (you will see Creating... and the VM resource at the same time) but after creation, the duplicate VMs will no longer appear.  This was fixed by this PR https://github.com/microsoft/vscode-azurevirtualmachines/pull/71.

I think that will be an acceptable solution :)
