### ISSUE TITLE
Create .ssh directory during createVM if it doesn't exist

### ISSUE THREAD

**Issue by hiten004** [microsoft/vscode-azurevirtualmachines#87]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureVirtualMachines.createVirtualMachine
Error type: Error
Error Message: Command "ssh-keygen -t rsa -b 4096 -f "C:\Users\Hiten\.ssh\azure_vmtest_rsa" -N "***"" failed with exit code "1":
Saving key "C:\\Users\\Hiten\\.ssh\\azure_vmtest_rsa" failed: No such file or directory
Generating public/private rsa key pair.

Version: 0.1.0
OS: win32
OS Release: 10.0.18362
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:127:278753
rejected extension.bundle.js:127:278278
```

</details>

**Comment by nturinski** [comment]
Hi @hiten004

Thanks for reporting.  Could you create a `.ssh` directory in your user folder `Hiten`?  That should resolve this issue.

**Comment by chrisdias** [comment]
I verified creating the `.ssh` folder works, but it is a poor first run experience.  The first time I tried creating a VM (without a passphrase) this was the output!

```
8:27:06 PM: Error: ***C***o***m***m***a***n***d*** ***"***s***s***h***-***k***e***y***g***e***n*** ***-***t*** ***r***s***a*** ***-***b*** ***4***0***9***6*** ***-***f*** ***"***C***:***\***U***s***e***r***s***\***c***h***r***i***s***\***.***s***s***h***\***a***z***u***r***e***_***c***d***i***a***s***-***d***e***v***-***r***e***a***c***t***_***r***s***a***"*** ***-***N*** ***"***"***"*** ***f***a***i***l***e***d*** ***w***i***t***h*** ***e***x***i***t*** ***c***o***d***e*** ***"***1***"***:***
***
***S***a***v***i***n***g*** ***k***e***y*** ***"***C***:***\***\***U***s***e***r***s***\***\***c***h***r***i***s***\***\***.***s***s***h***\***\***a***z***u***r***e***_***c***d***i***a***s***-***d***e***v***-***r***e***a***c***t***_***r***s***a***"*** ***f***a***i***l***e***d***:*** ***N***o*** ***s***u***c***h*** ***f***i***l***e*** ***o***r*** ***d***i***r***e***c***t***o***r***y***
***
***G***e***n***e***r***a***t***i***n***g*** ***p***u***b***l***i***c***/***p***r***i***v***a***t***e*** ***r***s***a*** ***k***e***y*** ***p***a***i***r***.***
***
***
```

Subsequent attempts (with a passphrase) gave me a proper error message in the output channel.
