### ISSUE TITLE
ssh-keygen failed

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-azurevirtualmachines#95]
I'm on a Windows 10 Home machine, which only has `ssh` and `ssh-keygen` available in CMD for some reason. The extension fails to generate the ssh key with error

```
Command "ssh-keygen -t rsa -b 4096 -f "C:\Users\fivei\.ssh\azure_uxtest_rsa" -N """ failed with exit code "1": 
'ssh-keygen' is not recognized as an internal or external command, operable program or batch file.
```

But I have `ssh-keygen` on my path, just only in CMD:

![image](https://user-images.githubusercontent.com/1186948/77460399-3e9e5880-6dbe-11ea-82e5-33e24328dd5b.png)

I'm not sure what the correct solution is, but maybe the command can fully qualify the path?

**Comment by fiveisprime** [comment]
Saw this in a user study today and realized that this also bombs the creation. That's a pretty big problem: ssh keygen fails so the VM fails to create, but it leaves the other resources hanging around in the subscription.

**Comment by fiveisprime** [comment]
Bumping this in priority because it's effectively broken for Win 10 Home users as it is. At the least it should successfully create the VM and gracefully handle the lack of SSH with a warning of some sort.

**Comment by fiveisprime** [comment]
P.S. Installing PuTTY seems to correct the issue... kind of. I'll open another issue for what happens next

**Comment by EricJizbaMSFT** [comment]
I thought ssh-keygen was installed when you install git, correct? I agree we need to improve this, but I feel like a big chunk of those "Win 10 Home users" probably have git installed

**Comment by nturinski** [comment]
So the Portal added some more options for SSH keys.  I think on a failure, we can fallback to something like this.  The advanced create scenario could be a prompt with the options listed below.

![image](https://user-images.githubusercontent.com/5290572/90843353-4420b000-e316-11ea-996a-9848914053d8.png)

**Comment by nturinski** [comment]
We can hold off on this until the next release.  It happens to 1% of users and will be resolved once we can use the Azure SSH Key API.
